language: node_js

cache:
    directories:
        - node_modules
        - bower_components

node_js:
  - '6'

before_install:
  - npm --version

install:
  - gem install sass compass
  - npm install -g bower grunt-cli
  - bower install
  - npm install

before_script:
  - cp app/scripts/config.js.example app/scripts/config.js

script:
  - grunt test
